(() => {
'use strict';
const Core=window.BakeryWSCore,Store=window.BakeryWSStore,Auth=window.BakeryWSAuth;
let state=Store.load(),session=null,currentView='dashboard',authMode='signin';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const id=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const settings=()=>state.settings||{};
const money=v=>{const c=Core.currencyMeta(settings().currency);return`${c.symbol}${Core.num(v).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:2})}`};
const pct=v=>v==null?'—':`${Core.num(v).toFixed(1)}%`;
const recipeById=x=>state.recipes.find(r=>r.id===x);
const customerById=x=>state.customers.find(c=>c.id===x);
const save=()=>Store.save(state);
const activeOrders=()=>state.orders.filter(o=>!['Delivered','Cancelled'].includes(o.status));
function formatDate(v){if(!v)return'—';const d=new Date(`${v}T12:00:00`);return d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
function statusBadge(s){const cls=s==='Delivered'?'green':s==='Cancelled'?'rose':s==='Confirmed'?'gold':'';return`<span class="badge ${cls}">${esc(s)}</span>`}
function setView(view){currentView=view;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));render()}
function render(){const titles={dashboard:['OVERVIEW','Good morning.'],orders:['ORDERS','Every order, under control.'],customers:['CUSTOMERS','Know who comes back.'],recipes:['RECIPES','Cost every bake with confidence.'],inventory:['INVENTORY','See what you have before you buy.'],production:['PRODUCTION','Know exactly what needs to be made.'],profit:['PROFITABILITY','See what the business keeps.'],settings:['SETTINGS','Make Bakery WS fit your business.']};const [eye,title]=titles[currentView]||titles.dashboard;$('#viewEyebrow').textContent=eye;$('#viewTitle').textContent=title;$('#currencyPill').textContent=settings().currency||'USD';$('#planPill').textContent=(settings().plan||'free').toUpperCase();$('#planLabel').textContent=`${Core.PLANS[settings().plan||'free'].name} plan`;const renderer={dashboard:renderDashboard,orders:renderOrders,customers:renderCustomers,recipes:renderRecipes,inventory:renderInventory,production:renderProduction,profit:renderProfit,settings:renderSettings}[currentView]||renderDashboard;renderer()}

function renderDashboard(){
 const p=Core.portfolio(activeOrders(),state.recipes,settings()),low=Core.lowStock(state.inventory),demand=Core.productionDemand(activeOrders(),state.recipes),tasks=(state.production||[]).filter(t=>!t.done),up=activeOrders().slice().sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,4);
 $('#viewRoot').innerHTML=`<div class="grid metrics"><div class="metric"><div class="label">Expected revenue</div><div class="value">${money(p.revenue)}</div><div class="meta">${activeOrders().length} active orders</div></div><div class="metric"><div class="label">Estimated profit</div><div class="value ${p.profit>=0?'positive':'negative'}">${money(p.profit)}</div><div class="meta">${pct(p.margin)} blended margin</div></div><div class="metric"><div class="label">Production demand</div><div class="value">${demand.reduce((s,x)=>s+x.units,0)}</div><div class="meta">units still to make</div></div><div class="metric"><div class="label">Low stock</div><div class="value">${low.length}</div><div class="meta">items at or below reorder level</div></div></div>
 <div class="grid two" style="margin-top:16px"><div class="card"><div class="section-head"><div><h2>Upcoming orders</h2><p>What needs your attention next.</p></div><button class="btn ghost" onclick="App.view('orders')">View all</button></div>${up.length?up.map(o=>{const c=customerById(o.customerId),f=Core.orderFinancials(o,state.recipes,settings());return`<div class="order-strip"><div class="order-date">${new Date(`${o.dueDate}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'}).replace(' ','\n')}</div><div class="order-strip-main"><strong>${esc(c?.name||'Customer')}</strong><small>${(o.items||[]).map(i=>`${esc(recipeById(i.recipeId)?.name||'Recipe')} × ${i.qty}`).join(' · ')}</small></div>${statusBadge(o.status)}<strong class="money">${money(f.revenue)}</strong></div>`}).join(''):'<div class="empty">No active orders yet.</div>'}</div>
 <div class="card"><div class="section-head"><div><h2>Today at a glance</h2><p>Production and stock signals.</p></div><button class="btn ghost" onclick="App.view('production')">Production</button></div><div class="alert-list">${low.slice(0,4).map(i=>`<div class="alert-row"><div><strong>${esc(i.name)}</strong><div class="muted">${i.onHand} ${esc(i.unit)} on hand · reorder at ${i.reorderAt}</div></div><span class="badge rose">Low stock</span></div>`).join('')||'<div class="alert-row"><strong>Inventory looks healthy</strong><span class="badge green">Good</span></div>'}${tasks.slice(0,3).map(t=>`<div class="alert-row"><div><strong>${esc(t.title)}</strong><div class="muted">Due ${formatDate(t.dueDate)}</div></div><span class="badge gold">Task</span></div>`).join('')}</div></div></div>`;
}

function renderOrders(){const rows=state.orders.slice().sort((a,b)=>a.dueDate.localeCompare(b.dueDate));$('#viewRoot').innerHTML=`<div class="card"><div class="section-head"><div><h2>Orders</h2><p>Revenue, true cost and expected profit for every order.</p></div><button class="btn primary" onclick="App.newOrder()">+ New order</button></div>${rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Customer</th><th>Due</th><th>Items</th><th>Status</th><th>Revenue</th><th>True cost</th><th>Profit</th><th></th></tr></thead><tbody>${rows.map(o=>{const c=customerById(o.customerId),f=Core.orderFinancials(o,state.recipes,settings());return`<tr><td><strong>${esc(c?.name||'Customer')}</strong><div class="muted">${esc(c?.email||'')}</div></td><td>${formatDate(o.dueDate)}</td><td>${(o.items||[]).map(i=>`${esc(recipeById(i.recipeId)?.name||'Recipe')} × ${i.qty}`).join('<br>')}</td><td>${statusBadge(o.status)}</td><td class="money">${money(f.revenue)}</td><td>${money(f.cost)}</td><td class="money ${f.profit>=0?'positive':'negative'}">${money(f.profit)}<div class="muted">${pct(f.margin)}</div></td><td><button class="btn ghost" onclick="App.editOrder('${o.id}')">Edit</button></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">No orders yet. Add your first order to start production and profit planning.</div>'}</div>`}

function renderCustomers(){const spend=new Map();state.orders.forEach(o=>{const f=Core.orderFinancials(o,state.recipes,settings());spend.set(o.customerId,(spend.get(o.customerId)||0)+f.revenue)});$('#viewRoot').innerHTML=`<div class="card"><div class="section-head"><div><h2>Customers</h2><p>Keep customer details and order value in one place.</p></div><button class="btn primary" onclick="App.newCustomer()">+ New customer</button></div>${state.customers.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Orders</th><th>Lifetime revenue</th><th></th></tr></thead><tbody>${state.customers.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.email||'—')}</td><td>${esc(c.phone||'—')}</td><td>${state.orders.filter(o=>o.customerId===c.id).length}</td><td class="money">${money(spend.get(c.id)||0)}</td><td><button class="btn ghost" onclick="App.editCustomer('${c.id}')">Edit</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No customers yet.</div>'}</div>`}

function renderRecipes(){const plan=settings().plan||'free';$('#viewRoot').innerHTML=`<div class="section-head"><div><h2>Recipes</h2><p>Ingredients + labor + packaging + overhead = true cost.</p></div><button class="btn primary" onclick="App.newRecipe()">+ New recipe</button></div><div class="grid three">${state.recipes.map(r=>{const c=Core.recipeCost(r,settings());return`<div class="card recipe-card"><span class="eyebrow">${esc(r.category||'RECIPE')}</span><h3>${esc(r.name)}</h3><div class="recipe-stats"><div><strong>${money(c.unitCost||0)}</strong><span>TRUE COST / UNIT</span></div><div><strong>${money(r.salePrice)}</strong><span>SELLING PRICE</span></div><div><strong class="${(c.margin||0)>=0?'positive':'negative'}">${pct(c.margin)}</strong><span>MARGIN</span></div></div><div class="muted" style="margin-top:12px">Suggested at ${c.targetMargin}% margin: <strong>${money(c.suggestedPrice||0)}</strong></div><div class="recipe-actions"><button class="btn ghost" onclick="App.editRecipe('${r.id}')">Edit</button><button class="btn secondary" onclick="App.recipeBreakdown('${r.id}')">Cost breakdown</button></div></div>`}).join('')}${state.recipes.length===0?'<div class="empty">No recipes yet.</div>':''}</div>${plan==='free'?`<div class="muted" style="margin-top:14px">Free plan: ${state.recipes.length}/${Core.PLANS.free.recipeLimit} recipes used.</div>`:''}`}

function renderInventory(){const low=Core.lowStock(state.inventory),shop=Core.shoppingList(activeOrders(),state.recipes,state.inventory);$('#viewRoot').innerHTML=`<div class="grid two"><div class="card"><div class="section-head"><div><h2>Inventory</h2><p>Current stock and reorder points.</p></div><button class="btn primary" onclick="App.newInventory()">+ Item</button></div>${state.inventory.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Ingredient</th><th>On hand</th><th>Reorder at</th><th>Status</th><th></th></tr></thead><tbody>${state.inventory.map(i=>`<tr><td><strong>${esc(i.name)}</strong></td><td>${i.onHand} ${esc(i.unit)}</td><td>${i.reorderAt} ${esc(i.unit)}</td><td>${i.onHand<=i.reorderAt?'<span class="badge rose">Low</span>':'<span class="badge green">Good</span>'}</td><td><button class="btn ghost" onclick="App.editInventory('${i.id}')">Edit</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No inventory yet.</div>'}</div><div class="card"><div class="section-head"><div><h2>Shopping list</h2><p>Calculated from active orders minus inventory on hand.</p></div></div>${shop.length?`<div class="alert-list">${shop.map(i=>`<div class="alert-row"><div><strong>${esc(i.name)}</strong><div class="muted">Need ${Core.round(i.qty,1)} ${esc(i.unit)} · have ${Core.round(i.onHand,1)}</div></div><strong>${Core.round(i.toBuy,1)} ${esc(i.unit)}</strong></div>`).join('')}</div>`:'<div class="empty">Nothing to buy for active orders.</div>'}<div class="muted" style="margin-top:12px">${low.length} item${low.length===1?'':'s'} currently below reorder level.</div></div></div>`}

function renderProduction(){if(!Core.canUse(settings().plan,'production')){return renderGate('Production planning is a Pro feature','Turn active orders into batch demand and production tasks automatically.')}const demand=Core.productionDemand(activeOrders(),state.recipes),tasks=state.production||[];$('#viewRoot').innerHTML=`<div class="grid two"><div class="card"><div class="section-head"><div><h2>Production demand</h2><p>Generated from every active order.</p></div></div>${demand.length?demand.map(d=>`<div class="alert-row"><div><strong>${esc(d.name)}</strong><div class="muted">${d.units} units ordered</div></div><strong>${d.batches} batch${d.batches===1?'':'es'}</strong></div>`).join(''):'<div class="empty">No active production demand.</div>'}</div><div class="card"><div class="section-head"><div><h2>Production tasks</h2><p>Simple execution checklist for V1.</p></div><button class="btn primary" onclick="App.newTask()">+ Task</button></div>${tasks.length?tasks.map(t=>`<label class="alert-row" style="cursor:pointer"><div><strong style="${t.done?'text-decoration:line-through;opacity:.55':''}">${esc(t.title)}</strong><div class="muted">Due ${formatDate(t.dueDate)}</div></div><input type="checkbox" style="width:auto" ${t.done?'checked':''} onchange="App.toggleTask('${t.id}')"></label>`).join(''):'<div class="empty">No production tasks.</div>'}</div></div>`}

function renderProfit(){if(!Core.canUse(settings().plan,'profitReports')){return renderGate('Full profitability is a Pro feature','Free users can see recipe true cost. Pro unlocks order and portfolio profitability across the business.')}const p=Core.portfolio(state.orders,state.recipes,settings());const recipeRows=state.recipes.map(r=>({r,c:Core.recipeCost(r,settings())})).sort((a,b)=>(b.c.margin||-999)-(a.c.margin||-999));$('#viewRoot').innerHTML=`<div class="grid metrics"><div class="metric"><div class="label">Revenue</div><div class="value">${money(p.revenue)}</div></div><div class="metric"><div class="label">True cost</div><div class="value">${money(p.cost)}</div></div><div class="metric"><div class="label">Estimated profit</div><div class="value ${p.profit>=0?'positive':'negative'}">${money(p.profit)}</div></div><div class="metric"><div class="label">Margin</div><div class="value">${pct(p.margin)}</div></div></div><div class="grid two" style="margin-top:16px"><div class="card"><div class="section-head"><div><h2>Product margins</h2><p>Best and weakest margin by recipe.</p></div></div>${recipeRows.map(x=>`<div class="alert-row"><div><strong>${esc(x.r.name)}</strong><div class="muted">True cost ${money(x.c.unitCost||0)} · sells ${money(x.r.salePrice)}</div></div><strong class="${(x.c.margin||0)>=0?'positive':'negative'}">${pct(x.c.margin)}</strong></div>`).join('')}</div><div class="card"><div class="section-head"><div><h2>Order profitability</h2><p>Revenue minus true product cost and order expenses.</p></div></div>${p.details.slice().sort((a,b)=>b.profit-a.profit).map(x=>`<div class="alert-row"><div><strong>${esc(customerById(x.order.customerId)?.name||'Customer')}</strong><div class="muted">${formatDate(x.order.dueDate)} · ${statusBadge(x.order.status)}</div></div><div style="text-align:right"><strong class="${x.profit>=0?'positive':'negative'}">${money(x.profit)}</strong><div class="muted">${pct(x.margin)}</div></div></div>`).join('')||'<div class="empty">No orders yet.</div>'}</div></div>`}

function renderSettings(){const preview=session?.mode==='preview';$('#viewRoot').innerHTML=`<div class="grid two"><div class="card"><div class="section-head"><div><h2>Business settings</h2><p>Defaults used across costing and pricing.</p></div></div><form id="settingsForm"><label>Business name<input name="businessName" value="${esc(settings().businessName||'')}"></label><label>Operating currency<select name="currency"><option value="USD" ${settings().currency==='USD'?'selected':''}>USD — US Dollar ($)</option><option value="ILS" ${settings().currency==='ILS'?'selected':''}>ILS — Israeli Shekel (₪)</option></select></label><div class="form-grid"><label>Hourly labor rate<input name="hourlyRate" type="number" step=".01" min="0" value="${settings().hourlyRate||0}"></label><label>Overhead per labor hour<input name="overheadPerHour" type="number" step=".01" min="0" value="${settings().overheadPerHour||0}"></label><label>Default target margin %<input name="targetMargin" type="number" step="1" min="0" max="95" value="${settings().targetMargin||45}"></label></div><div class="form-actions"><button class="btn primary">Save settings</button></div></form></div><div class="card"><div class="section-head"><div><h2>Plan</h2><p>Bakery WS will launch with Free and Pro.</p></div></div><div class="plan-choice"><div class="plan-option ${settings().plan==='free'?'active':''}"><span class="badge">FREE</span><h3>Start organized</h3><ul><li>Up to ${Core.PLANS.free.recipeLimit} recipes</li><li>Up to ${Core.PLANS.free.monthlyOrderLimit} orders / month</li><li>Recipe true cost & pricing</li><li>Inventory & shopping list</li></ul>${preview?'<button class="btn secondary wide" onclick="App.setPlan(\'free\')">Preview Free</button>':''}</div><div class="plan-option ${settings().plan==='pro'?'active':''}"><span class="badge gold">PRO</span><h3>Run for profit</h3><ul><li>Unlimited recipes & orders</li><li>Production planning</li><li>Full order profitability</li><li>Advanced business insights</li></ul>${preview?'<button class="btn primary wide" onclick="App.setPlan(\'pro\')">Preview Pro</button>':'<button class="btn primary wide" disabled>Billing coming next</button>'}</div></div><p class="muted" style="margin-top:14px">Plan limits are V1 beta defaults and can be changed before launch.</p></div></div>`;$('#settingsForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.settings={...settings(),businessName:String(f.get('businessName')||'Bakery WS'),currency:String(f.get('currency')||'USD'),hourlyRate:Core.num(f.get('hourlyRate')),overheadPerHour:Core.num(f.get('overheadPerHour')),targetMargin:Core.num(f.get('targetMargin'))};save();render()}}
function renderGate(title,text){$('#viewRoot').innerHTML=`<div class="card"><div class="gate"><span class="badge gold">PRO</span><h3>${esc(title)}</h3><p>${esc(text)}</p><button class="btn primary" onclick="App.view('settings')">See Free vs Pro</button></div></div>`}

function openModal(kicker,title,html){$('#modalKicker').textContent=kicker||'';$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').hidden=false}
function closeModal(){$('#modal').hidden=true;$('#modalBody').innerHTML=''}
function customerOptions(selected=''){return state.customers.map(c=>`<option value="${c.id}" ${selected===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}
function recipeOptions(selected=''){return state.recipes.map(r=>`<option value="${r.id}" ${selected===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}
function orderItemRow(item={}){const r=recipeById(item.recipeId);return`<div class="ingredient-row order-item"><label>Recipe<select class="oi-recipe" onchange="App.syncOrderPrice(this)"><option value="">Choose recipe</option>${recipeOptions(item.recipeId)}</select></label><label>Qty<input class="oi-qty" type="number" min="1" step="1" value="${item.qty||1}"></label><label style="grid-column:auto">Unit price<input class="oi-price" type="number" min="0" step=".01" value="${item.unitPrice??r?.salePrice??0}"></label><div></div><button type="button" class="remove-row" onclick="this.closest('.order-item').remove()">×</button></div>`}
function newOrder(raw={}){if(!state.customers.length)return newCustomer(()=>newOrder(raw));if(!state.recipes.length)return alert('Add a recipe first.');const o={id:'',customerId:state.customers[0]?.id||'',dueDate:new Date().toISOString().slice(0,10),status:'New',deliveryFee:0,discount:0,extraCost:0,items:[],...raw};openModal('ORDER',o.id?'Edit order':'New order',`<form id="orderForm"><div class="form-grid"><label>Customer<select name="customerId">${customerOptions(o.customerId)}</select></label><label>Due date<input name="dueDate" type="date" required value="${esc(o.dueDate)}"></label><label>Status<select name="status">${['New','Confirmed','In production','Ready','Delivered','Cancelled'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Delivery fee<input name="deliveryFee" type="number" min="0" step=".01" value="${o.deliveryFee||0}"></label><label>Discount<input name="discount" type="number" min="0" step=".01" value="${o.discount||0}"></label><label>Extra order cost<input name="extraCost" type="number" min="0" step=".01" value="${o.extraCost||0}"></label><div class="full"><label>Products</label><div id="orderItems" class="ingredient-rows">${(o.items.length?o.items:[{}]).map(orderItemRow).join('')}</div><button class="btn secondary" type="button" onclick="App.addOrderItem()">+ Add product</button></div></div><div class="form-actions"><button type="button" class="btn ghost" data-close-modal>Cancel</button><button class="btn primary">Save order</button></div></form>`);$('#orderForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),items=$$('.order-item').map(row=>({recipeId:row.querySelector('.oi-recipe').value,qty:Math.max(1,Math.round(Core.num(row.querySelector('.oi-qty').value))),unitPrice:Math.max(0,Core.num(row.querySelector('.oi-price').value))})).filter(i=>i.recipeId);if(!items.length)return alert('Add at least one product.');const obj={...o,id:o.id||id('ord'),customerId:f.get('customerId'),dueDate:f.get('dueDate'),status:f.get('status'),deliveryFee:Core.num(f.get('deliveryFee')),discount:Core.num(f.get('discount')),extraCost:Core.num(f.get('extraCost')),items,createdAt:o.createdAt||new Date().toISOString()};const ex=state.orders.find(x=>x.id===obj.id);if(ex)Object.assign(ex,obj);else state.orders.push(obj);save();closeModal();setView('orders')}}
function newCustomer(afterSave,raw={}){if(typeof afterSave==='object'){raw=afterSave;afterSave=null}const c={id:'',name:'',email:'',phone:'',...raw};openModal('CUSTOMER',c.id?'Edit customer':'New customer',`<form id="customerForm"><label>Name<input name="name" required value="${esc(c.name)}"></label><label>Email<input name="email" type="email" value="${esc(c.email)}"></label><label>Phone<input name="phone" value="${esc(c.phone)}"></label><div class="form-actions"><button type="button" class="btn ghost" data-close-modal>Cancel</button><button class="btn primary">Save customer</button></div></form>`);$('#customerForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),obj={...c,id:c.id||id('cus'),name:String(f.get('name')).trim(),email:String(f.get('email')||''),phone:String(f.get('phone')||'')};const ex=state.customers.find(x=>x.id===obj.id);if(ex)Object.assign(ex,obj);else state.customers.push(obj);save();closeModal();if(afterSave)afterSave();else render()}}
function ingredientRow(i={}){return`<div class="ingredient-row"><label>Ingredient<input class="ri-name" value="${esc(i.name||'')}"></label><label>Qty<input class="ri-qty" type="number" min="0" step=".01" value="${i.qty||0}"></label><label>Unit<input class="ri-unit" value="${esc(i.unit||'g')}"></label><label>Cost / unit<input class="ri-cost" type="number" min="0" step=".0001" value="${i.unitCost||0}"></label><button type="button" class="remove-row" onclick="this.closest('.ingredient-row').remove()">×</button></div>`}
function newRecipe(raw={}){const editing=!!raw.id;if(!editing&&!Core.withinLimit(settings().plan,'recipes',state.recipes.length))return showUpgrade('Free plan recipe limit reached','Upgrade to Pro to add unlimited recipes.');const r={id:'',name:'',category:'Cookies',yieldUnits:12,salePrice:0,targetMargin:settings().targetMargin||45,laborMinutes:30,packagingPerUnit:0,fixedOverhead:0,wastePct:3,ingredients:[],...raw};openModal('RECIPE',editing?'Edit recipe':'New recipe',`<form id="recipeForm"><div class="form-grid"><label>Recipe name<input name="name" required value="${esc(r.name)}"></label><label>Category<input name="category" value="${esc(r.category)}"></label><label>Yield / batch<input name="yieldUnits" type="number" min="1" step="1" required value="${r.yieldUnits}"></label><label>Selling price / unit<input name="salePrice" type="number" min="0" step=".01" value="${r.salePrice}"></label><label>Active labor minutes<input name="laborMinutes" type="number" min="0" step="1" value="${r.laborMinutes}"></label><label>Packaging / unit<input name="packagingPerUnit" type="number" min="0" step=".01" value="${r.packagingPerUnit}"></label><label>Fixed overhead / batch<input name="fixedOverhead" type="number" min="0" step=".01" value="${r.fixedOverhead}"></label><label>Waste %<input name="wastePct" type="number" min="0" step=".1" value="${r.wastePct}"></label><label>Target margin %<input name="targetMargin" type="number" min="0" max="95" step="1" value="${r.targetMargin}"></label><div class="full"><label>Ingredients</label><div id="recipeIngredients" class="ingredient-rows">${(r.ingredients.length?r.ingredients:[{}]).map(ingredientRow).join('')}</div><button type="button" class="btn secondary" onclick="App.addIngredient()">+ Add ingredient</button></div></div><div class="form-actions"><button type="button" class="btn ghost" data-close-modal>Cancel</button><button class="btn primary">Save recipe</button></div></form>`);$('#recipeForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),ingredients=$$('#recipeIngredients .ingredient-row').map(row=>({name:row.querySelector('.ri-name').value.trim(),qty:Core.num(row.querySelector('.ri-qty').value),unit:row.querySelector('.ri-unit').value.trim()||'g',unitCost:Core.num(row.querySelector('.ri-cost').value)})).filter(i=>i.name&&i.qty>0),obj={...r,id:r.id||id('rec'),name:String(f.get('name')).trim(),category:String(f.get('category')||'Recipe'),yieldUnits:Math.max(1,Math.round(Core.num(f.get('yieldUnits')))),salePrice:Core.num(f.get('salePrice')),laborMinutes:Core.num(f.get('laborMinutes')),packagingPerUnit:Core.num(f.get('packagingPerUnit')),fixedOverhead:Core.num(f.get('fixedOverhead')),wastePct:Core.num(f.get('wastePct')),targetMargin:Core.num(f.get('targetMargin')),ingredients};const ex=state.recipes.find(x=>x.id===obj.id);if(ex)Object.assign(ex,obj);else state.recipes.push(obj);save();closeModal();setView('recipes')}}
function recipeBreakdown(id){const r=recipeById(id),c=Core.recipeCost(r,settings());openModal('TRUE COST',r.name,`<div class="grid metrics" style="grid-template-columns:repeat(2,1fr)"><div class="metric"><div class="label">Ingredients + waste</div><div class="value">${money(c.ingredientCost)}</div></div><div class="metric"><div class="label">Labor</div><div class="value">${money(c.laborCost)}</div></div><div class="metric"><div class="label">Packaging</div><div class="value">${money(c.packagingCost)}</div></div><div class="metric"><div class="label">Overhead</div><div class="value">${money(c.overheadCost)}</div></div></div><div class="card" style="margin-top:14px"><div class="alert-row"><strong>Batch true cost</strong><strong>${money(c.batchCost)}</strong></div><div class="alert-row"><strong>True cost / unit</strong><strong>${money(c.unitCost||0)}</strong></div><div class="alert-row"><strong>Current selling price</strong><strong>${money(c.salePrice)}</strong></div><div class="alert-row"><strong>Suggested price at ${c.targetMargin}% margin</strong><strong class="positive">${money(c.suggestedPrice||0)}</strong></div></div>`)}
function newInventory(raw={}){const i={id:'',name:'',onHand:0,unit:'g',reorderAt:0,...raw};openModal('INVENTORY',i.id?'Edit inventory item':'New inventory item',`<form id="inventoryForm"><label>Ingredient<input name="name" required value="${esc(i.name)}"></label><div class="form-grid"><label>On hand<input name="onHand" type="number" min="0" step=".01" value="${i.onHand}"></label><label>Unit<input name="unit" value="${esc(i.unit)}"></label><label>Reorder at<input name="reorderAt" type="number" min="0" step=".01" value="${i.reorderAt}"></label></div><div class="form-actions"><button type="button" class="btn ghost" data-close-modal>Cancel</button><button class="btn primary">Save item</button></div></form>`);$('#inventoryForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),obj={...i,id:i.id||id('inv'),name:String(f.get('name')).trim(),onHand:Core.num(f.get('onHand')),unit:String(f.get('unit')||'unit'),reorderAt:Core.num(f.get('reorderAt'))};const ex=state.inventory.find(x=>x.id===obj.id);if(ex)Object.assign(ex,obj);else state.inventory.push(obj);save();closeModal();render()}}
function newTask(){const today=new Date().toISOString().slice(0,10);openModal('PRODUCTION','New task',`<form id="taskForm"><label>Task<input name="title" required placeholder="e.g. Bake cookie batches"></label><label>Due date<input name="dueDate" type="date" required value="${today}"></label><div class="form-actions"><button type="button" class="btn ghost" data-close-modal>Cancel</button><button class="btn primary">Add task</button></div></form>`);$('#taskForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.production.push({id:id('task'),title:String(f.get('title')).trim(),dueDate:String(f.get('dueDate')),done:false});save();closeModal();render()}}
function showUpgrade(title,text){openModal('FREE PLAN',title,`<div class="gate"><span class="badge gold">PRO</span><h3>${esc(title)}</h3><p>${esc(text)}</p><button class="btn primary" onclick="App.closeModal();App.view('settings')">See plans</button></div>`)}

async function initAuth(){session=await Auth.currentSession();if(session)return showApp();$('#authScreen').hidden=false;$('#appShell').hidden=true}
function showApp(){session=session||Store.session();$('#authScreen').hidden=true;$('#appShell').hidden=false;$('#accountEmail').textContent=session?.email||'Preview';render()}
function bind(){
 $('#mainNav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)setView(b.dataset.view)});$$('.sidebar-bottom [data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('#globalAdd').onclick=()=>newOrder();$('#signOutBtn').onclick=async()=>{await Auth.signOut();location.reload()};$$('[data-auth-mode]').forEach(b=>b.onclick=()=>{authMode=b.dataset.authMode;$$('[data-auth-mode]').forEach(x=>x.classList.toggle('active',x===b));$('#authSubmit').textContent=authMode==='signin'?'Sign in':'Create account';$('#authPassword').autocomplete=authMode==='signin'?'current-password':'new-password'});$('#authForm').onsubmit=async e=>{e.preventDefault();const msg=$('#authMessage'),email=$('#authEmail').value.trim(),password=$('#authPassword').value;msg.textContent='';try{session=authMode==='signin'?await Auth.signIn(email,password):await Auth.signUp(email,password);showApp()}catch(err){msg.textContent=err.message||'Unable to continue.'}};$('#previewBtn').onclick=()=>{session=Auth.preview();showApp()};document.addEventListener('click',e=>{if(e.target.matches('[data-close-modal]'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal').hidden)closeModal()})}

window.App={view:setView,newOrder,editOrder:id=>newOrder(state.orders.find(o=>o.id===id)),addOrderItem:()=>$('#orderItems').insertAdjacentHTML('beforeend',orderItemRow({})),syncOrderPrice:sel=>{const row=sel.closest('.order-item'),r=recipeById(sel.value);if(r)row.querySelector('.oi-price').value=r.salePrice},newCustomer,editCustomer:id=>newCustomer(state.customers.find(c=>c.id===id)),newRecipe,editRecipe:id=>newRecipe(state.recipes.find(r=>r.id===id)),addIngredient:()=>$('#recipeIngredients').insertAdjacentHTML('beforeend',ingredientRow({})),recipeBreakdown,newInventory,editInventory:id=>newInventory(state.inventory.find(i=>i.id===id)),newTask,toggleTask:id=>{const t=state.production.find(x=>x.id===id);if(t){t.done=!t.done;save();render()}},setPlan:plan=>{if(session?.mode!=='preview')return;state.settings.plan=plan;save();render()},closeModal};
bind();initAuth();
})();