(function(root){
  'use strict';
  let client=null;
  const HYDRATE_KEY='bakery_ws_cloud_hydrated_v1';
  function configured(){const c=root.BAKERY_WS_CONFIG||{};return !!(c.supabaseUrl&&c.supabasePublishableKey&&root.supabase)}
  function getClient(){if(!configured())return null;if(!client)client=root.supabase.createClient(root.BAKERY_WS_CONFIG.supabaseUrl,root.BAKERY_WS_CONFIG.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return client}
  function accountSession(user){return{mode:'account',email:user?.email||'',userId:user?.id||''}}
  async function ensureProfile(user){const c=getClient();if(!c||!user?.id)return null;const store=root.BakeryWSStore;const local=store?.load?.()||store?.seed?.()||{};const plan=local?.settings?.plan||'free',currency=local?.settings?.currency||'USD';const {error:profileError}=await c.from('profiles').upsert({user_id:user.id,email:user.email||'',plan,currency,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(profileError)throw profileError;const {data:remote,error:readError}=await c.from('user_data').select('data').eq('user_id',user.id).maybeSingle();if(readError)throw readError;if(remote?.data&&Object.keys(remote.data).length){store?.replaceLocal?.(remote.data);return remote.data}const initial=local&&Object.keys(local).length?local:(store?.seed?.()||{});const {error:insertError}=await c.from('user_data').upsert({user_id:user.id,data:initial,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(insertError)throw insertError;return initial}
  async function currentSession(){const local=root.BakeryWSStore?.session?.();if(local?.mode==='preview')return local;const c=getClient();if(!c)return null;const {data,error}=await c.auth.getSession();if(error)throw error;const user=data?.session?.user;if(!user)return null;const s=accountSession(user);root.BakeryWSStore?.setSession?.(s);const workspace=await ensureProfile(user);const token=`${user.id}:${JSON.stringify(workspace||{}).length}`;if(sessionStorage.getItem(HYDRATE_KEY)!==token){sessionStorage.setItem(HYDRATE_KEY,token);location.reload()}return s}
  async function signIn(email,password){const c=getClient();if(!c)throw new Error('Account backend is not connected yet. Use Preview mode while the backend is being configured.');const {data,error}=await c.auth.signInWithPassword({email,password});if(error)throw error;if(!data?.session?.user)throw new Error('Unable to start a signed-in session.');const s=accountSession(data.session.user);root.BakeryWSStore?.setSession?.(s);await ensureProfile(data.session.user);location.reload();return s}
  async function signUp(email,password){const c=getClient();if(!c)throw new Error('Account backend is not connected yet. Use Preview mode while the backend is being configured.');const {data,error}=await c.auth.signUp({email,password});if(error)throw error;if(!data?.session?.user)throw new Error('Account created. Check your email to confirm your address, then sign in.');const s=accountSession(data.session.user);root.BakeryWSStore?.setSession?.(s);await ensureProfile(data.session.user);location.reload();return s}
  async function saveWorkspace(state){const c=getClient();if(!c)return false;const {data}=await c.auth.getSession();const user=data?.session?.user;if(!user)return false;const clean={...state,settings:{...(state?.settings||{})}};const {error}=await c.from('user_data').upsert({user_id:user.id,data:clean,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;const {error:profileError}=await c.from('profiles').upsert({user_id:user.id,email:user.email||'',plan:clean.settings?.plan||'free',currency:clean.settings?.currency||'USD',updated_at:new Date().toISOString()},{onConflict:'user_id'});if(profileError)throw profileError;return true}
  async function signOut(){const local=root.BakeryWSStore?.session?.();sessionStorage.removeItem(HYDRATE_KEY);if(local?.mode==='preview'){root.BakeryWSStore.setSession(null);return}const c=getClient();if(c)await c.auth.signOut();root.BakeryWSStore?.setSession?.(null)}
  function preview(){const session={mode:'preview',email:'preview@bakeryws.app',userId:'preview'};root.BakeryWSStore.setSession(session);return session}
  root.BakeryWSAuth={configured,currentSession,signIn,signUp,signOut,preview,saveWorkspace,ensureProfile,getClient};
})(typeof globalThis!=='undefined'?globalThis:this);